### ISSUE TITLE
Nested Double and Single quotes throws error

### ISSUE THREAD

**Issue by jfeltkamp** [rackberg/para#11]
A shell command line like this:
   git commit -m "RWRD8-537: created new tag for change 'region: content' included."

... throws this message: 
dara:   error: pathspec 'content included.' did not match any file(s) known to git.
alra:   error: pathspec 'content included.' did not match any file(s) known to git.
bobi:   error: pathspec 'content included.' did not match any file(s) known to git.
bora:   error: pathspec 'content included.' did not match any file(s) known to git.
rare:   error: pathspec 'content included.' did not match any file(s) known to git.

**Comment by rackberg** [comment]
I'll close this ticket, because I am unable to reproduce the bug.
